#!/bin/bash
# SOF-ELK® Supporting script
# (C)2021 Lewes Technology Consulting, LLC
#
# This runs scripts after a dhcp lease is secured or renewed

# run dhclient.d scripts in an emulated environment

if [ ${NM_DISPATCHER_ACTION} == "up" ]; then
    kill -HUP $( pidof agetty )
fi
