from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="backend.as.number",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-as#field-as-number",
    ),
    ECSField(
        name="backend.as.organization.name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-as#field-as-organization-name",
    ),
    ECSField(
        name="backend.geo.asnstr",
        description="Runtime field created via Elasticsearch template",
        labels_type="N/A",
        config_mapped="component-mappings-geohash.json",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="backend.geo.city_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-city-name",
    ),
    ECSField(
        name="backend.geo.continent_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-continent-code",
    ),
    ECSField(
        name="backend.geo.country_iso_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-country-iso-code",
    ),
    ECSField(
        name="backend.geo.country_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-country-name",
    ),
    ECSField(
        name="backend.geo.location",
        description="created by geoip filter",
        labels_type="all",
        field_type="geo_point",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-location",
    ),
    ECSField(
        name="backend.geo.postal_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-postal-code",
    ),
    ECSField(
        name="backend.geo.region_iso_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-region-iso-code",
    ),
    ECSField(
        name="backend.geo.region_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-region-name",
    ),
    ECSField(
        name="backend.geo.timezone",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-timezone",
    ),
    ECSField(
        name="backend.ip",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="backend.port",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="SOF-ELK",
    ),
]
