from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="cisco.asa.action",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="cisco.asa.connection_id",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.destination_username",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.mapped_destination.ip",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.mapped_destination.port",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.mapped_source.ip",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.mapped_source.port",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.policy_id",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="cisco.asa.reason",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="cisco.asa.source_username",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-cisco#_cisco_asa",
    ),
    ECSField(
        name="cisco.asa.username",
        description="from cisco_asa grok patterns",
        labels_type="syslog",
        config_mapped="6018-cisco_asa.conf",
        ecs_source="SOF-ELK",
    ),
]
