from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="client.as.number",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-as#field-as-number",
    ),
    ECSField(
        name="client.as.organization.name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-as#field-as-organization-name",
    ),
    ECSField(
        name="client.domain",
        labels_type="syslog",
        config_mapped="6012-dhcpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-domain",
    ),
    ECSField(
        name="client.geo.asnstr",
        description="Runtime field created via Elasticsearch template",
        labels_type="N/A",
        config_mapped="component-mappings-geohash.json",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="client.geo.city_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-city-name",
    ),
    ECSField(
        name="client.geo.continent_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-continent-code",
    ),
    ECSField(
        name="client.geo.country_iso_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-country-iso-code",
    ),
    ECSField(
        name="client.geo.country_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-country-name",
    ),
    ECSField(
        name="client.geo.location",
        description="created by geoip filter",
        labels_type="all",
        field_type="geo_point",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-location",
    ),
    ECSField(
        name="client.geo.postal_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-postal-code",
    ),
    ECSField(
        name="client.geo.region_iso_code",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-region-iso-code",
    ),
    ECSField(
        name="client.geo.region_name",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-region-name",
    ),
    ECSField(
        name="client.geo.timezone",
        description="created by geoip filter",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-geo#field-geo-timezone",
    ),
    ECSField(
        name="client.ip",
        labels_type="kubernetes",
        config_mapped="6952-kubernetes.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-ip",
    ),
    ECSField(
        name="client.ip",
        labels_type="syslog",
        config_mapped="6012-dhcpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-ip",
    ),
    ECSField(
        name="client.mac",
        labels_type="syslog",
        config_mapped="6012-dhcpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-mac",
    ),
    ECSField(
        name="client.port",
        labels_type="kubernetes",
        config_mapped="6952-kubernetes.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-port",
    ),
    ECSField(
        name="client.port",
        labels_type="microsoft365",
        config_mapped="6701-microsoft365.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-client#field-client-port",
    ),
    ECSField(
        name="client.user.name",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="SOF-ELK",
    ),
]
