from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="google_workspace.actor.key",
        description="Only present when actor.type is KEY. Can be the consumer_key of the requestor for OAuth 2LO API requests or an identifier for robot accounts.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.actor.type",
        description="The type of actor. Values can be: USER: Another user in the same domain. EXTERNAL_USER: A user outside the domain. KEY: A non-human actor.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.asp_id",
        description="The application specific password ID.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.edition",
        description="The Google Workspace edition.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.enabled",
        description="The enabled application.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.id",
        description="The application ID.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.licences_order_number",
        description="Order number used to redeem licenses.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.licences_purchased",
        description="Number of licences purchased.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.name",
        description="The application's name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.application.package_id",
        description="The mobile application package ID.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.domain.alias",
        description="The domain alias.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.domain.name",
        description="The primary domain name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.domain.secondary_name",
        description="The secondary domain name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.admin.group.email",
        description="The group's primary email address.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.group.priorities",
        description="Group priorities.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.managed_configuration",
        description="The name of the managed configuration.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.new_value",
        description="The new value for the setting.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.non_featured_services_selection",
        description="Non-featured services selection. For a list of possible values refer to https://developers.google.com/admin-sdk/reports/v1/appendix/activity/admin-application-settings#FLASHLIGHT_EDU_NON_FEATURED_SERVICES_SELECTED",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.old_value",
        description="The old value for the setting.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.org_unit.full",
        description="The org unit full path including the root org unit name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.org_unit.name",
        description="The organizational unit name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.setting.description",
        description="The setting name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.setting.name",
        description="The setting name.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.admin.user_defined_setting.name",
        description="The name of the user-defined setting.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.chat.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.drive.destination_folder_id",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.drive.destination_folder_title",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.drive.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.drive.new_value",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.drive.old_value",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.drive.source_folder_id",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.drive.source_folder_title",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.event.name",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.event.type",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.groups.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.id.application.name",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.kind",
        description="The type of API resource, mapped from kind in the original payload. More details can be found at https://developers.google.com/admin-sdk/reports/v1/reference/activities/list",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.login.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.mobile.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.organization.domain",
        description="The domain that is affected by the report's event.",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="filebeat",
        ecs_reference="https://www.elastic.co/docs/reference/beats/filebeat/exported-fields-google_workspace#_google_workspace",
    ),
    ECSField(
        name="google_workspace.token.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="google_workspace.user_accounts.event_parameters",
        description="created by split_kv_to_fields.rb",
        labels_type="gws",
        config_mapped="6951-gws.conf",
        ecs_source="SOF-ELK",
    ),
]
