from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="kape.executable_info",
        labels_type="kape_evtxlogs",
        config_mapped="6504-kape_evtxecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.log_level",
        labels_type="kape_evtxlogs",
        config_mapped="6504-kape_evtxecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.map_description",
        labels_type="kape_evtxlogs",
        config_mapped="6504-kape_evtxecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.copied",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.hasads",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.inuse",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.isads",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.name_type",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="kape.mft.timestomped",
        labels_type="kape_filesystem",
        config_mapped="6501-kape_mftecmd.conf",
        ecs_source="SOF-ELK",
    ),
]
