from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="related.hash",
        labels_type="hayabusa",
        config_mapped="6605-hayabusa.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-hash",
    ),
    ECSField(
        name="related.hash",
        labels_type="plaso",
        config_mapped="6601-plaso.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-hash",
    ),
    ECSField(
        name="related.hash",
        labels_type="syslog",
        config_mapped="6010-snare.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-hash",
    ),
    ECSField(
        name="related.ip",
        labels_type="all",
        config_mapped="8050-postprocess-ip_addresses.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-ip",
    ),
    ECSField(
        name="related.mac",
        labels_type="all",
        config_mapped="8053-postprocess-mac.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="related.port",
        labels_type="all",
        config_mapped="8051-postprocess_ports.conf",
        ecs_source="SOF-ELK",
    ),
    ECSField(
        name="related.user",
        labels_type="hayabusa",
        config_mapped="6605-hayabusa.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-user",
    ),
    ECSField(
        name="related.user",
        labels_type="plaso",
        config_mapped="6601-plaso.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-user",
    ),
    ECSField(
        name="related.user",
        labels_type="syslog",
        config_mapped="6010-snare.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-related#field-related-user",
    ),
]
