from sof_elk.lib.ecs import ECSField

FIELDS = [
    ECSField(
        name="url.domain",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-domain",
    ),
    ECSField(
        name="url.original",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-domain",
    ),
    ECSField(
        name="url.password",
        labels_type="zeek_http",
        config_mapped="6201-zeek_http.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-password",
    ),
    ECSField(
        name="url.path",
        labels_type="azure",
        config_mapped="6801-azure.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-path",
    ),
    ECSField(
        name="url.path",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-path",
    ),
    ECSField(
        name="url.path",
        labels_type="kubernetes",
        config_mapped="6952-kubernetes.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-path",
    ),
    ECSField(
        name="url.path",
        labels_type="zeek_http",
        config_mapped="6201-zeek_http.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-path",
    ),
    ECSField(
        name="url.query",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-query",
    ),
    ECSField(
        name="url.scheme",
        labels_type="httpdlog",
        config_mapped="6100-httpd.conf",
        ecs_source="ECS",
        ecs_reference="https://www.elastic.co/docs/reference/ecs/ecs-url#field-url-scheme",
    ),
]
