---
# Ansible file supporting the build of a SOF-ELK(R) standalone system
# (C)2026 Lewes Technology Consulting, LLC

- name: Delete default indices known to cause problems
  ansible.builtin.uri:
    url: http://localhost:9200/{{ item }}
    method: DELETE
    status_code: [200, 404]
  with_items:
    - .entity_analytics.watchlists.default
  register: index_delete_result
  changed_when: index_delete_result.status == 200
  tags: elasticsearch

- name: Wait for Elasticsearch to be ready
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/wait_for_es.sh'
  tags: sof-elk_finalize

- name: Run the post-merge script, which also loads all dashboards
  ansible.builtin.command: '/usr/local/sof-elk/supporting-scripts/post_merge.sh'
  tags: sof-elk_finalize

- name: Restart Kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
  tags: sof-elk_finalize
